name: "Apply"

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.0.2
  PLAN_NAME: plan-${{ github.head_ref }}
  WORKING_DIR: terraform/main.tf

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/*
    steps:

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials
        with:
          aws-access-key-id: aws-access-key-id ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: echo 'your plans saved to the artifact and now you can run the apply.yaml workflow'