name: Apply Branch

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction
          - production

env:
  TERRAFORM_PATH: ./terraform/${{ github.event.inputs.environment }}
  TERRAFORM_PLAN: terraform-plan
  STATUS: merged
  STAGE: ${{ github.event.inputs.environment }}
  WORKFLOW: s3.yaml

jobs:
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PATH }}
    steps:
      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3
        
      - name: Download artifact
        id: download-artifact
        if: ${{ github.event.inputs.environment == 'nonproduction' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: s3.yaml
          workflow_conclusion: success
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.STAGE, env.TERRAFORM_PLAN) }}
          path: ${{ env.TERRAFORM_PATH }}

      - name: Upload Artifact To PR Actions
        id: uploadMerged
        if: ${{ github.event.inputs.environment == 'nonproduction' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.STAGE, env.TERRAFORM_PLAN) }}
          path: ${{ env.TERRAFORM_PATH }}

