name: Apply Branch

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction
          - production

env:
  TERRAFORM_PATH: ./terraform/${{ github.event.inputs.environment }}
  TERRAFORM_PLAN: terraform-plan
  STATUS: merged
  STAGE: ${{ github.event.inputs.environment }}
  WORKFLOW: s3.yaml


jobs:
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PATH }}
    steps:
      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3
        
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"

      
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: s3.yaml
          workflow_conclusion: success
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.STAGE, env.TERRAFORM_PLAN) }}
          path: ${{ env.TERRAFORM_PATH }}

      - name: Apply Lower Envs
        id: apply
        if: ${{ github.event.inputs.environment != 'production' }}
        run: |
          echo "Applying TF"
          
      - name: Apply Prod
        id: apply-prod
        if: ${{ (github.event.inputs.environment == 'production') && (steps.branch-name.outputs.current_branch == 'main') }}
        run: |
          echo "Applying tf to prod"
          
      - name: Upload Artifact To PR Actions
        id: uploadMerged
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.STAGE, env.TERRAFORM_PLAN) }}
          path: ${{ env.TERRAFORM_PATH }}

