name: Test WF

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: "Environment Name"
        options:
          - dev
          - staging
          - production

env:
  STAGE: ${{ github.event.inputs.environment }}

jobs:
  deploy-it:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ${{ env.DEFAULT_PATH }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Branch protection
        run: |
          echo ${{ github.ref }}
          if [ ${{ env.STAGE == production }} && ${{ github.ref != refs/heads/main }} ];   
          then  
              echo Invalid branch selection, production must be run on main
              exit1  
          else  
              echo Running Apply on ${{ github.ref }};   
          fi  


