name: Manual Apply

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction

env:
  TERRAFORM_PATH: ./terraform
  TERRAFORM_PLAN: terraform-plan
  STATUS: merged
  ARTIFACT_NAME: ${{ github.event.inputs.environment }}
  WORKFLOW: s3.yaml


jobs:
  apply-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          workflow: env.WORKFLOW
          workflow_conclusion: success
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.ARTIFACT_NAME, env.TERRAFORM_PLAN) }}
          search_artifacts: true
          if_no_artifact_found: fail
          path: ${{ env.TERRAFORM_PATH }}/${{ github.event.inputs.environment }}


