name: Manual Apply

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction

env:
  TERRAFORM_PATH: ./terraform/${{ github.event.inputs.environment }}
  TERRAFORM_PLAN: terraform-plan
  STATUS: merged
  ARTIFACT_NAME: ${{ github.event.inputs.environment }}
  WORKFLOW: s3.yaml


jobs:
  apply-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.ARTIFACT_NAME, env.TERRAFORM_PLAN) }}
          workflow: s3.yaml
          search_workflow: true
          workflow_conclusion: success
          path: ${{ env.TERRAFORM_PATH }}

      - name: Upload Artifact To PR Actions
        id: uploadMerged
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format('{0}-{1}-{2}', env.STATUS, env.ARTIFACT_NAME, env.TERRAFORM_PLAN) }}
          path: ${{ env.TERRAFORM_PATH }}

