name: Manual Apply

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction
          - production
      behavior:
        type: choice
        required: true
        description: 'Plan or Apply'
        options:
          - Plan from branch
          - Apply from PR

env:
  TERRAFORM_PATH: ./terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  BUCKET_NAME: "tf-practice-bucket"

jobs:
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PATH }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3

      - name: Setup TF
        id: setup
        uses: hashicorp/setup-terraform@v2

      - name: Download artifact
        if: github.event.pull_request.merged == true
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: s3.yaml
          workflow_conclusion: success
          name: test-infra
          search_artifacts: true
          if_no_artifact_found: fail

      - name: Init
        id: init
        run: terraform init

      - name: Apply Terraform
        id: Apply
        run: terraform apply -auto-approve -input=false