name: Manual Apply

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction

env:
  TERRAFORM_PATH: ./terraform
  ARTIFACT_NAME: merged-${{ github.events.inputs.environmet }}-terraform-plan
  WORKFLOW: s3.yaml


jobs:
  apply-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PATH }}
    steps:
      - name: Check out repository code
        id: chckoutRepo
        uses: actions/checkout@v3

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: env.WORKFLOW
          workflow_conclusion: success
          name: env.ARTIFACT_NAME
          search_artifacts: true
          if_no_artifact_found: warn
          path: ${{ env.TERRAFORM_PATH }}/${{ github.events.inputs.environmet }}

      - name: Print Contents
        id: content
        run: cat nonproduction.txt

