name: Manual Apply

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 'Environment Name'
        options:
          - nonproduction
          - preproduction
          - production
      behavior:
        type: choice
        required: true
        description: 'Plan or Apply'
        options:
          - Plan from branch
          - Apply from PR

env:
  TERRAFORM_PATH: ./terraform
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  BUCKET_NAME: "tf-practice-bucket"

jobs:
  tf-plan-to-s3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TERRAFORM_PATH }}

