name: TF PLAN

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
    types:
      - opened
      - closed
      - synchronize

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TERRAFORM_VERSION: 1.2.2
  TERRAFORM_PATH: ./terraform
  PLAN_NAME: plan-${{ github.head_ref }}

jobs:
  plan-infrastructure:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        stage: [ 'dev', 'prod', 'test' ]
      fail-fast: true
    defaults:
      run:
        working-directory: ${{ format ('{0}/{1}', env.TERRAFORM_PATH, matrix.stage) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload Plan
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ format ('{0}/{1}', matrix.stage, env.PLAN_NAME) }}
          path: ${{env.TERRAFORM_PATH }}/${{ matrix.stage }}/${{ format ('{0}/{1}', matrix.stage, env.PLAN_NAME) }}

      - name: Download Artifact
        if: github.event.pull_request.merged == true
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_conclusion: success
          pr: ${{ github.event.pull_request.number }}
          name: ${{ env.PLAN_NAME }}
          path: ${{env.TERRAFORM_PATH }}/${{ matrix.stage }}/${{ format ('{0}/{1}', matrix.stage, env.PLAN_NAME) }}

      - name: Finished
        id: finished
        run: |
          echo Workflow run was a success, proceed to manual dispatch to apply terraform.
          echo Please Work Dambit
         
