name: Upload to s3

on:
  workflow_dispatch:
    
jobs:
  write-to-s3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: airuleguy/s3-cp-action@master
      env:
        FILE: test.txt
        SOURCE_PATH: ./test
        DESTINATION_KEY: /s3/key/
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'

